server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: persona-servicio
          uri: lb://persona-servicio
          predicates:
            - Path=/api/personas/**
        - id: foto-servicio
          uri: lb://foto-servicio
          predicates:
            - Path=/fotos/**
        